version: "2"

services:
  postgresql:
    image: "bitnami/postgresql:latest"
    container_name: postgresql
    environment:
      - POSTGRESQL_USERNAME=jasmin
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=jasmin_db
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/bitnami/postgresql

volumes:
  postgresql_data:
    driver: local
